CREATE USER "fastuser"@"localhost" IDENTIFIED BY "fastuser_pass";

GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT,
REFERENCES, RELOAD
ON *.* TO "fastuser"@"localhost" WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS itbcis;
